/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.umg.ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Edgar Mayorga
 */
public class JFDesktop extends javax.swing.JFrame {
    JIFAvion ventanaInterna;
    JIFAvion ventanaInterna2;
    JIFAvion ventanaInterna3;
    JIFManualUsuario ventanaPdf;
    
    public JFDesktop() {
        initComponents();
        this.setSize(1400, 900);
        this.setLocationRelativeTo(null);
        this.setTitle("CONTROL LISTA DE PASAJEROS TACAs.");
    }
    
    
    public void mostrarVentanaAvion(int numeroAvion) throws IOException{
        if(numeroAvion == 1){
            if (ventanaInterna == null || ventanaInterna.isClosed()) {
                ventanaInterna = new JIFAvion(numeroAvion);
                ventanaInterna.setTitle("1 - LISTADO DE PASAJEROS AVION " + numeroAvion);
                ventanaInterna.setVisible(true);
                dpPanelVentanas.add(ventanaInterna);

                try {
                    ventanaInterna.setSelected(true);
                } catch (Exception ex) {

                }
                repaint();
            } else {
                System.out.println("La ventana del avion 1 ya se encuentra abierta.");
            }
        }
        if(numeroAvion == 2){
            if (ventanaInterna2 == null || ventanaInterna2.isClosed()) {
                ventanaInterna2 = new JIFAvion(numeroAvion);
                ventanaInterna2.setTitle("2 - LISTADO DE PASAJEROS AVION " + numeroAvion);
                ventanaInterna2.setVisible(true);
                dpPanelVentanas.add(ventanaInterna2);

                try {
                    ventanaInterna2.setSelected(true);
                } catch (Exception ex) {

                }
                repaint();
            } else {
                System.out.println("La ventana del avion 2 ya se encuentra abierta.");
            }
        }
        if(numeroAvion == 3){
            if (ventanaInterna3 == null || ventanaInterna2.isClosed()) {
                ventanaInterna3 = new JIFAvion(numeroAvion);
                ventanaInterna3.setTitle("3 - LISTADO DE PASAJEROS AVION " + numeroAvion);
                ventanaInterna3.setVisible(true);
                dpPanelVentanas.add(ventanaInterna3);

                try {
                    ventanaInterna3.setSelected(true);
                } catch (Exception ex) {

                }
                repaint();
            } else {
                System.out.println("La ventana del avion 3 ya se encuentra abierta.");
            }
        }
    }
    
    public void mostrarVentanaManualUsuario(){
        if (ventanaPdf == null || ventanaPdf.isClosed()) {
                ventanaPdf = new JIFManualUsuario();
                ventanaPdf.setTitle("MANUAL DE USARIO");
                ventanaPdf.setVisible(true);
                dpPanelVentanas.add(ventanaPdf);

                try {
                    ventanaPdf.setSelected(true);
                } catch (Exception ex) {

                }
                repaint();
            } else {
                System.out.println("La ventana del manual de usuario ya se encuentra abierta.");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPanelVentanas = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        miAvion1 = new javax.swing.JMenuItem();
        miAvion2 = new javax.swing.JMenuItem();
        miAvion3 = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miManualUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        dpPanelVentanas.setOpaque(false);
        getContentPane().add(dpPanelVentanas);

        jMenu1.setText("Archivo");

        jMenu3.setText("Lista de pasajeros");
        jMenu3.setActionCommand("Nuevo...");

        miAvion1.setText("Avión 1");
        miAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAvion1ActionPerformed(evt);
            }
        });
        jMenu3.add(miAvion1);

        miAvion2.setText("Avión 2");
        miAvion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAvion2ActionPerformed(evt);
            }
        });
        jMenu3.add(miAvion2);

        miAvion3.setText("Avión 3");
        miAvion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAvion3ActionPerformed(evt);
            }
        });
        jMenu3.add(miAvion3);

        jMenu1.add(jMenu3);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        miManualUsuario.setText("Manual de usuario");
        miManualUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManualUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(miManualUsuario);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAvion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAvion1ActionPerformed
        try {
            // TODO add your handling code here:
            mostrarVentanaAvion(1);
        } catch (IOException ex) {
            Logger.getLogger(JFDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miAvion1ActionPerformed

    private void miAvion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAvion2ActionPerformed
        try {
            // TODO add your handling code here:
            mostrarVentanaAvion(2);
        } catch (IOException ex) {
            Logger.getLogger(JFDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miAvion2ActionPerformed

    private void miAvion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAvion3ActionPerformed
        try {
            // TODO add your handling code here:
            mostrarVentanaAvion(3);
        } catch (IOException ex) {
            Logger.getLogger(JFDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miAvion3ActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miManualUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManualUsuarioActionPerformed
        // TODO add your handling code here:
        mostrarVentanaManualUsuario();
    }//GEN-LAST:event_miManualUsuarioActionPerformed

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPanelVentanas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAvion1;
    private javax.swing.JMenuItem miAvion2;
    private javax.swing.JMenuItem miAvion3;
    private javax.swing.JMenuItem miManualUsuario;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
