/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.umg.ui;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.MyAnnotationCallback;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author Edgar Mayorga
 */
public class JIFManualUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFManualUsuario
     */
    public JIFManualUsuario(){
        initComponents();
        this.setSize(900, 750);
        this.setLocation(225, 25);
        cargarManualUsuario();
    }
    
    public void cargarManualUsuario(){
        try{
            
            String ruta = "./recursos/MANUAL_DE_USUARIO.pdf";
            //JOptionPane.showMessageDialog(null, "PATH " + ruta, "ERROR", JOptionPane.ERROR_MESSAGE);
            File file = new File(ruta);
            String path = file.getPath();

            //String path = new File("").getCanonicalPath();// + "\\src\\org\\umg\\recursos\\MANUAL DE USUARIO.pdf";
            //String path = System.getProperty("user.dir") + "\\src\\org\\umg\\recursos\\MANUAL DE USUARIO.pdf";
            System.out.println(path);
            ///JOptionPane.showMessageDialog(null, "La ruta del archivo es: " + path, "ERROR", JOptionPane.ERROR_MESSAGE);

            SwingController controller = new SwingController();
            SwingViewBuilder factory = new SwingViewBuilder(controller);
            JPanel viewComponente = factory.buildViewerPanel();
            ComponentKeyBinding.install(controller, viewComponente);
            controller.getDocumentViewController().setAnnotationCallback(new MyAnnotationCallback(controller.getDocumentViewController()));
            controller.openDocument(path);
            spManualUsuario.setViewportView(viewComponente);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar el manual." + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spManualUsuario = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MANUAL DE USUARIO");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(spManualUsuario);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spManualUsuario;
    // End of variables declaration//GEN-END:variables
}
